"""Add equipo to registro

Revision ID: b2158ffc0f82
Revises: 
Create Date: 2025-10-01 14:54:25.352577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2158ffc0f82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_registro_backup')
    op.drop_table('consultor_modulos')
    with op.batch_alter_table('base_registro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_base_registro_fecha_date'))
        batch_op.drop_column('fecha_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_date', sa.DATE(), nullable=True))
        batch_op.create_index(batch_op.f('idx_base_registro_fecha_date'), ['fecha_date'], unique=False)

    op.create_table('consultor_modulos',
    sa.Column('consultor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('modulo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['consultor_id'], ['consultor.id'], name=op.f('fk_cm_cons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo.id'], name=op.f('fk_cm_mod'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consultor_id', 'modulo_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('base_registro_backup',
    sa.Column('id', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('fecha', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('modulo', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('cliente', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('nro_caso_cliente', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('nro_caso_interno', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('tipo_tarea', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('consultor', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('hora_inicio', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('hora_fin', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tiempo_invertido', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tiempo_facturable', mysql.FLOAT(), nullable=True),
    sa.Column('horas_adicionales', mysql.FLOAT(), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('consolidado_cliente', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('dia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('anio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ocupacion_azure', mysql.VARCHAR(length=600), nullable=True),
    sa.Column('tarea_azure', mysql.VARCHAR(length=600), nullable=True),
    sa.Column('horas_convertidas', mysql.FLOAT(), nullable=True),
    sa.Column('promedio', mysql.FLOAT(), nullable=True),
    sa.Column('extemporaneo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('equipo', mysql.VARCHAR(length=120), nullable=True),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
